### ISSUE TITLE
No Banner sizes support

### ISSUE THREAD

**Issue by Hakim-Allaoui** [dnaextrim/flutter_ironsource_x#2] opened 2021-07-10 18:44 UTC
Hello man,
Thanks very much for the amazing plugin, I just wondering if you can add support for other banner sizes, 
also, I have a problem with banners, that they disappear when I back to previous screen.

**Comment by elkhalifte** [comment] 2021-09-05 12:11
Looking for the fix for this aswell

**Comment by dnaextrim** [comment] 2021-09-07 17:34
Today I've tried to make support for banner sizes, but for some sizes, it can't display ads and it seems the problem is in the main library of IronSourceSDK. My latest update this can be the solution to this problem.

Thank you

**Closed** 2021-09-11 14:05 UTC
